- name: Setup AAAAA
  hosts: coreos:dnf:desktop
  gather_facts: true
  vars_files:
    - "../inventories/prod/host_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/all.yaml"
  vars:
    main_user: core
  
  tasks:
    - name: Setup AAAAA | Setup variables (detect container)
      ansible.builtin.set_fact:
        node_is_container: "{{ (ansible_facts['virtualization_tech_guest'] | default([]) | length) > 0 }}"
    
    - name: Setup AAAAA | Setup variables (compute once, reuse everywhere)
      ansible.builtin.set_fact:
        service_dir: "{{ '/etc/systemd/system' if node_is_container else '/home/' ~ main_user ~ '/.config/systemd/user' }}"
        quadlet_dir: "{{ '/etc/containers/systemd' if node_is_container else '/home/' ~ main_user ~ '/.config/containers/systemd' }}"
        file_owner: "{{ 'root' if node_is_container else main_user }}"
        file_group: "{{ 'root' if node_is_container else main_user }}"
        calculated_become: "{{ node_is_container }}"
        systemd_scope: "{{ 'system' if node_is_container else 'user' }}"
    
    - name: Setup AAAAA | Systemd Podman Quadlet
      ansible.builtin.template:
        src: "../files/AAAAA/AAAAA.container"
        dest: "{{ quadlet_dir }}/AAAAA.container"
        comment_start_string: "# BEGIN_OF_COMMENT"
        comment_end_string: "# END_OF_COMMENT"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0640"
      become: "{{ calculated_become }}"
      register: systemd_podman_quadlet_output
      
    - name: Setup AAAAA | Systemd Service
      ansible.builtin.template:
        src: "../files/AAAAA/AAAAA.service"
        dest: "{{ service_dir }}/AAAAA.service"
        comment_start_string: "# BEGIN_OF_COMMENT"
        comment_end_string: "# END_OF_COMMENT"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0640"
      become: "{{ calculated_become }}"
      register: systemd_service_output
    
    - name: Setup AAAAA | ensures data directory exists
      ansible.builtin.file:
        path: "/var/mnt/data/AAAAA"
        state: directory
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0750"
      become: true
      register: data_dir_output
      
    - name: Setup AAAAA | ensures directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0750"
      become: "{{ calculated_become }}"
      register: data_dir_output
      loop:
        - "{{ some_path }}"
        - "{{ some_path }}/data"
        - "{{ some_path }}/etc"
        - "{{ some_path }}/tls"
    
    - name: Setup AAAAA | Restart service
      ansible.builtin.systemd:
        daemon_reload: true
        name: AAAAA.service
        state: restarted
        enabled: true
        scope: "{{ systemd_scope }}"
      become: "{{ calculated_become }}"
      when: >
        systemd_podman_quadlet_output.changed or
        data_dir_output.changed
