- name: Setup AAAAA
  hosts: coreos:dnf:desktop
  gather_facts: true
  vars_files:
    - "../inventories/prod/secret_vars/all.yaml"

  pre_tasks:
    - name: Gather per-host secret files
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - "../inventories/prod/secret_vars/{{ inventory_hostname }}/base.yaml"
      when: lookup('ansible.builtin.fileglob', item) | length > 0

  tasks:
    - name: Setup AAAAA | Setup variables (detect container)
      ansible.builtin.set_fact:
        run_as_root: "{{ ansible_facts['virtualization_tech_guest'] | default('') in ['lxc', 'container'] }}"
    
    - name: Setup AAAAA | Setup variables (compute once, reuse everywhere)
      ansible.builtin.set_fact:
        service_dir: "{{ '/etc/systemd/system' if run_as_root else '/home/' ~ main_user ~ '/.config/systemd/user' }}"
        quadlet_dir: "{{ '/etc/containers/systemd' if run_as_root else '/home/' ~ main_user ~ '/.config/containers/systemd' }}"
        file_owner: "{{ 'root' if run_as_root else main_user }}"
        file_group: "{{ 'root' if run_as_root else main_user }}"
        calculated_become: "{{ run_as_root }}"
        systemd_scope: "{{ 'system' if run_as_root else 'user' }}"
        
    - name: Setup AAAAA | Info about running user
      ansible.builtin.debug:
        msg:
          - "Run as root: {{ run_as_root }}"
          - "Service dir: {{ service_dir }}"
          - "Quadlet dir: {{ quadlet_dir }}"
          - "User: {{ file_owner }}"
          - "Group: {{ file_group }}"
          - "Become: {{ calculated_become }}"
          - "Scope: {{ systemd_scope }}"
    
    - name: Setup AAAAA | Systemd Podman Quadlet
      ansible.builtin.template:
        src: "../files/AAAAA/AAAAA.container"
        dest: "{{ quadlet_dir }}/AAAAA.container"
        comment_start_string: "# BEGIN_OF_COMMENT"
        comment_end_string: "# END_OF_COMMENT"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0640"
      become: "{{ calculated_become }}"
      register: systemd_podman_quadlet_output
      notify: Restart service
      
    - name: Setup AAAAA | Systemd Service
      ansible.builtin.template:
        src: "../files/AAAAA/AAAAA.service"
        dest: "{{ service_dir }}/AAAAA.service"
        comment_start_string: "# BEGIN_OF_COMMENT"
        comment_end_string: "# END_OF_COMMENT"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0640"
      become: "{{ calculated_become }}"
      register: systemd_service_output
      notify: Restart service
    
    - name: Setup AAAAA | ensures data directory exists
      ansible.builtin.file:
        path: "/var/mnt/data/AAAAA"
        state: directory
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0750"
      become: "{{ calculated_become }}"
      register: data_dir_output
      notify: Restart service
      
    - name: Setup AAAAA | ensures directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0750"
      become: "{{ calculated_become }}"
      register: data_dir_output
      loop:
        - "{{ some_path }}"
        - "{{ some_path }}/data"
        - "{{ some_path }}/etc"
        - "{{ some_path }}/tls"
      notify: Restart service
    
    - name: Setup AAAAA | Restart service
      ansible.builtin.systemd:
        daemon_reload: true
        name: AAAAA.service
        state: restarted
        enabled: true
        scope: "{{ systemd_scope }}"
      become: "{{ calculated_become }}"
      when: >
        systemd_podman_quadlet_output.changed or
        data_dir_output.changed

  handlers:
    - name: Restart service
      ansible.builtin.systemd:
        daemon_reload: true
        name: AAAAA.service
        state: restarted
        enabled: true
        scope: "{{ systemd_scope }}"
      become: "{{ calculated_become }}"
