- name: Install SFTPGo
  hosts: wyse01.tailnet-ba52.ts.net
  gather_facts: true
  vars_files:
    - "../inventories/prod/secret_vars/all.yaml"

  pre_tasks:
    - name: Gather per-host secret files
      ansible.builtin.include_vars:
        file: "{{ item }}"
      loop:
        - "../inventories/prod/secret_vars/{{ inventory_hostname }}/base.yaml"
      when: lookup('ansible.builtin.fileglob', item) | length > 0

  tasks:
    - name: Install SFTPGo | Ensure data directory exists
      ansible.builtin.file:
        path: "/var/mnt/data1/sftpgo/data"
        state: directory
        owner: "{{ main_user }}"
        group: "{{ main_user }}"
        mode: '0755'
      become: true
      
    - name: Install SFTPGo | Ensure home directory exists
      ansible.builtin.file:
        path: "/var/mnt/data1/sftpgo/home"
        state: directory
        owner: "{{ main_user }}"
        group: "{{ main_user }}"
        mode: '0755'
      become: true

    - name: Install SFTPGo | Install systemd quadlet service
      ansible.builtin.template:
        src: "../files/sftpgo/sftpgo.container"
        dest: "/home/{{ main_user }}/.config/containers/systemd/"
        comment_start_string: "# BEGIN_OF_COMMENT"
        comment_end_string: "# END_OF_COMMENT"
        owner: "{{ main_user }}"
        group: "{{ main_user }}"
        mode: "0600"
      become: true
      register: install_service_output

    - name: Install SFTPGo | Restart SFTPGo service
      ansible.builtin.systemd:
        daemon_reload: true
        name: sftpgo.service
        state: restarted
        enabled: true
        scope: user
      when: >
        install_service_output.changed
