- name: Setup Home Assistant
  hosts: wyse01.tailnet-ba52.ts.net
  gather_facts: true
  vars_files:
    - "../inventories/prod/host_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/{{ inventory_hostname }}.yaml"
    - "../inventories/prod/secret_vars/all.yaml"
  vars:
    main_user: core
  
  tasks:
    - name: Setup Home Assistant | Setup variables (detect container)
      ansible.builtin.set_fact:
        node_is_container: "true"
    
    - name: Setup Home Assistant | Setup variables (compute once, reuse everywhere)
      ansible.builtin.set_fact:
        service_dir: "{{ '/etc/systemd/system' if node_is_container else '/home/' ~ main_user ~ '/.config/systemd/user' }}"
        quadlet_dir: "{{ '/etc/containers/systemd' if node_is_container else '/home/' ~ main_user ~ '/.config/containers/systemd' }}"
        file_owner: "{{ 'root' if node_is_container else main_user }}"
        file_group: "{{ 'root' if node_is_container else main_user }}"
        calculated_become: "{{ node_is_container }}"
        systemd_scope: "{{ 'system' if node_is_container else 'user' }}"
    
    - name: Setup Home Assistant | Ensure homeassistant directory exists
      ansible.builtin.file:
        path: "/var/mnt/data1/homeassistant/config"
        state: directory
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: '0750'
      become: "{{ calculated_become }}"
      register: data_dir_output
      notify: Restart service

    - name: Setup Home Assistant | Install systemd quadlet service (system)
      ansible.builtin.template:
        src: "../files/homeassistant/homeassistant.container"
        dest: "{{ quadlet_dir }}/homeassistant.container"
        comment_start_string: "# BEGIN_OF_COMMENT"
        comment_end_string: "# END_OF_COMMENT"
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: '0640'
      become: "{{ calculated_become }}"
      register: install_service_output
      notify: Restart service
    
  handlers:
    - name: Restart service
      ansible.builtin.systemd:
        daemon_reload: true
        name: homeassistant.service
        state: restarted
        enabled: true
        scope: "{{ systemd_scope }}"
      become: "{{ calculated_become }}"
